version: '3.8'

services:
  web:
    build: .
    restart: always
    networks:
      - webinar-net
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_SECRET=${BOT_SECRET}
      - WEBSITE_URL=https://webinars.bojumbohost.pp.ua
    volumes:
      - storage-data:/app/data

  bot:
    build: .
    restart: always
    networks:
      - webinar-net
    command: node bot.js
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_SECRET=${BOT_SECRET}
      - WEBSITE_URL=http://web:3000
    depends_on:
      - web

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    networks:
      - webinar-net
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

networks:
  webinar-net:
    driver: bridge

volumes:
  storage-data:
