version: '3.8'

services:
  web:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_SECRET=${BOT_SECRET}
      - WEBSITE_URL=https://webinar.bojumbo.com
    # Прибираємо прямий монтаж файлів, які можуть бути відсутні
    volumes:
      - storage-data:/app/data

  bot:
    build: .
    restart: always
    command: node bot.js
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_SECRET=${BOT_SECRET}
      - WEBSITE_URL=http://web:3000
    depends_on:
      - web

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  storage-data:
